spring.application.name=Sync
server.port=8081

# ?? ??? (?? ?? ??) ? ?? ???(js/css)? API ?? ??? UTF-8? ??
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# MySQL ??


# JPA ??


# Mustache


# ?? Python CLIP ??

# ?? Last.fm API
# https://www.last.fm/api ?? ?? ??

# ?? Spotify API (?? ?? ? ??) ????????????????????????
# https://developer.spotify.com ?? ??


# ?? ?? ??? (OAuth) ?????????????????????????????????????
# https://console.cloud.google.com ? API ? ??? ? ??? ?? ??
# ??? ???? URI? ?? google.redirect.uri ?? ??? ???? ?


# ?? ??? ??? (OAuth) ????????????????????????????????????
# https://developers.naver.com/apps ? ?????? ??
# Callback URL? ?? naver.redirect.uri
