spring.application.name=Sync
server.port=8081

# ?? ??? (?? ?? ??) ? ?? ???(js/css)? API ?? ??? UTF-8? ??
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# MySQL ??
spring.datasource.url=jdbc:mysql://localhost:3306/sync_database
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Mustache
spring.mustache.suffix=.mustache
spring.mustache.prefix=classpath:/templates/
spring.mustache.charset=UTF-8

# ?? Python CLIP ??
clip.server.url=http://localhost:8000

# ?? Last.fm API
# https://www.last.fm/api ?? ?? ??


# ?? Spotify API (?? ?? ? ??) ????????????????????????
# https://developer.spotify.com ?? ??



# ?? ?? ??? (OAuth) ?????????????????????????????????????
# https://console.cloud.google.com ? API ? ??? ? ??? ?? ??
# ??? ???? URI? ?? google.redirect.uri ?? ??? ???? ?


# ?? ??? ??? (OAuth) ????????????????????????????????????
# https://developers.naver.com/apps ? ?????? ??
# Callback URL? ?? naver.redirect.uri
